export const Types = {
    GET_MONSTERS: "GET_MONSTERS",
    SET_ACTIVE_MONSTER_MODAL: "SET_ACTIVE_MONSTER_MODAL",
    SET_MONSTER_MODAL_VISIBILITY: "SET_MONSTER_MODAL_VISIBILITY",
}

export default Types;
